const Video_Tecnologia_Deshumaniza = new ActivityContent({
  creator: Creator_Curiosamente,

  title: "¿La tecnología nos deshumaniza?",

  type: "video",

  url: "https://www.youtube.com/watch?v=oL_mHK5v2OU&ab_channel=CuriosaMente",

  youtube_embed_url: "https://www.youtube.com/embed/oL_mHK5v2OU",

  text: [
    {
      title: "Introducción",
      paragraphs: [
        "Es muy frecuente que escuchemos que la tecnología nos deshumaniza, es decir, que nos despoja de las características que nos hacen humanos.",
        "Pero ¿qué es la tecnología? y ¿nos hace menos humanos?",
      ],
    },
    {
      title: "La palabra tecnología",
      paragraphs: [
        "Relacionamos la palabra “Tecnología” con cosas muy nuevas, generalmente electrónicas, pero se trata de un concepto muy antiguo.",
        "“Tecnología” es una palabra de raíces griegas.",
        "“Tekné” significa “arte” u “oficio”, y “logos” estudio o conocimiento.",
      ],
    },
    {
      title: "¿Qué la tecnología?",
      paragraphs: [
        "La tecnología es el conocimiento aplicado a la solución de un problema o al mejoramiento de alguna capacidad humana.",
        "La aplicación de la tecnología nos permite, por ejemplo:",
        "Desplazarnos más lejos y más rápido.",
        "Aplicar más fuerza con menos esfuerzo.",
        "Ver las cosas lejanas como si estuvieran cerca y las cosas pequeñas verlas grandes.",
        "Hacer llegar nuestra voz muy lejos y escuchar lo que está lejano.",
        "Recordar cosas que podríamos olvidar.",
        "¡Inventar nuevas tecnologías!",
        "Hasta los inventos más humildes y rústicos son aplicaciones tecnológicas.",
        "Entonces ¿un lápiz, una bicicleta, una computadora o un videojuego nos deshumanizan?",
      ],
    },
    {
      title: "¿Qué nos hace humanos?",
      paragraphs: [
        "Primero tendríamos que preguntarnos ¿qué tenemos los humanos que no tengan muy desarrolladas otros seres?",
        "Para empezar, a diferencia de otros animales que se adaptan a su entorno o perecen, los humanos somos capaces de adaptar el entorno a nuestras necesidades o gustos.",
        "¿Es eso lo que nos hace humanos?",
      ],
    },
    {
      title: "Un poco de filosofía",
      paragraphs: [
        "La discusión es filosófica y profunda, pero podemos estar de acuerdo en algunas características que los seres humanos hemos desarrollado más:",
        "El razonamiento: muy vinculado a un lenguaje complejo que nos permite pensar y comunicar ideas abstractas.",
        "Gracias al lenguaje podemos discutir acerca de eventos pasados, posibles futuros, incluso imaginarios.",
        "El lenguaje en sí mismo es una tecnología, y la escritura, que nos permite conservar ideas para futuras generaciones, es también una tecnología.",
        "La moral y el derecho: el ponernos más o menos de acuerdo en qué debemos y qué no debemos hacer.",
        "¿Sabías que uno de los primeros ejemplos de escritura de la historia es el Código de Hammurabi?",
        "Es un conjunto de leyes escritas en Babilonia alrededor del año 1700 antes de Cristo.",
        "El arte: esas actividades que nos permiten expresar y compartir emociones e ideas, como la danza, el teatro, la pintura y la escultura, están profundamente asociadas con aplicaciones de la tecnología.",
        "La guerra: somos la única especie que, gracias a las tecnologías para matar, es capaz de extinguirse a sí misma.",
      ],
    },
    {
      title: "La tecnología nos ha  humanizado",
      paragraphs: [
        "Así pues, resulta que la tecnología, más bien, es la que nos ha humanizado, para bien o para mal.",
        "Pero al final, no es la tecnología en sí misma la que nos transforma, sino el uso que hacemos de ella, ya que sólo es capaz de potenciar nuestras propias habilidades.",
        "Como dijo el científico y escritor alemán Georg Christoph Lichtemberg:",
        "“Aquello tuvo el efecto que por general tienen los buenos libros. Hizo más tontos a los tontos, más listos a los listos y los miles restantes… quedaron ilesos”.",
        "Ni el mejor procesador de texto puede hacernos escritores, una calculadora científica no nos ara inteligentisimos matemáticos, una sofisticada tableta de dibujo no nos convertirá en artistas.",
        "Finalmente la tecnología nos permite hacer con más efectividad, eficiencia y precisión aquello que ya sabemos hacer.",
        "Por eso, la mejor manera de aprovechar las tecnologías es desarrollar primero… todo aquello que podemos hacer sin ellas.",
        "¡Curiosamente!",
      ],
    },
  ],

  // Cognates
  cognates: [
    {
      in_text: "frecuente",
      in_text_translation: "frequent",
      english: "frequent",
      spanish: "frecuente",
    },
    {
      in_text: "tecnología",
      in_text_translation: "technology",
      english: "technology",
      spanish: "la tecnología",
    },
    {
      in_text: "características",
      in_text_translation: "characteristics",
      english: "characteristics",
      spanish: "la característica",
    },
    {
      in_text: "deshumaniza",
      in_text_translation: "dehumanizes",
      english: "dehumanize",
      spanish: "deshumanizar",
    },
    {
      in_text: "humanos",
      in_text_translation: "humans",
      english: "human",
      spanish: "el humano",
    },
    {
      in_text: "generalmente",
      in_text_translation: "generally",
      english: "generally",
      spanish: "generalmente",
    },
    {
      in_text: "electrónicas",
      in_text_translation: "electronic",
      english: "electronic",
      spanish: "electrónico",
    },
    {
      in_text: "concepto",
      in_text_translation: "concept",
      english: "concept",
      spanish: "el concepto",
    },
    {
      in_text: "arte",
      in_text_translation: "art",
      english: "art",
      spanish: "el arte",
    },
    {
      in_text: "estudio",
      in_text_translation: "study",
      english: "study",
      spanish: "el estudio",
    },
    {
      in_text: "aplicado",
      in_text_translation: "applied",
      english: "apply",
      spanish: "aplicar",
    },
    {
      in_text: "solución",
      in_text_translation: "solution",
      english: "solution",
      spanish: "la solución",
    },
    {
      in_text: "fuerza",
      in_text_translation: "force",
      english: "force",
      spanish: "la fuerza",
    },
    {
      in_text: "esfuerzo",
      in_text_translation: "effort",
      english: "effort",
      spanish: "el esfuerzo",
    },
    {
      in_text: "voz",
      in_text_translation: "voice",
      english: "voice",
      spanish: "voz",
    },
    {
      in_text: "inventos",
      in_text_translation: "inventions",
      english: "invention",
      spanish: "el invento",
    },
    {
      in_text: "rústico",
      in_text_translation: "rustic",
      english: "rustic",
      spanish: "rústico",
    },
    {
      in_text: "bicicleta",
      in_text_translation: "bicycle",
      english: "bicycle",
      spanish: "la bicicleta",
    },
    {
      in_text: "computadora",
      in_text_translation: "computer",
      english: "computer",
      spanish: "la computadora",
    },
    {
      in_text: "otros",
      in_text_translation: "others",
      english: "other",
      spanish: "el otro",
    },
    {
      in_text: "animales",
      in_text_translation: "animals",
      english: "animal",
      spanish: "el animal",
    },
    {
      in_text: "adaptan",
      in_text_translation: "adapt",
      english: "adapt",
      spanish: "adaptar",
    },
    {
      in_text: "necesidades",
      in_text_translation: "necessities",
      english: "necessity",
      spanish: "la necesidad",
    },
    {
      in_text: "discusión",
      in_text_translation: "discussion",
      english: "discussion",
      spanish: "la discusión",
    },
    {
      in_text: "filosófica",
      in_text_translation: "philosophical",
      english: "philosophical",
      spanish: "la filosofía",
    },
    {
      in_text: "razonamiento",
      in_text_translation: "reasoning",
      english: "reasoning",
      spanish: "el razonamiento",
    },
    {
      in_text: "lenguaje",
      in_text_translation: "language",
      english: "lenguaje",
      spanish: "el lenguaje",
    },
    {
      in_text: "complejo",
      in_text_translation: "complex",
      english: "complex",
      spanish: "complejo",
    },
    {
      in_text: "ideas",
      in_text_translation: "ideas",
      english: "idea",
      spanish: "la idea",
    },
    {
      in_text: "abstractas",
      in_text_translation: "abstract",
      english: "abstract",
      spanish: "abstracto",
    },
    {
      in_text: "moral",
      in_text_translation: "moral",
      english: "moral",
      spanish: "la moral",
    },
    {
      in_text: "historia",
      in_text_translation: "history",
      english: "history",
      spanish: "la historia",
    },
    {
      in_text: "Código",
      in_text_translation: "code",
      english: "code",
      spanish: "el código",
    },
    {
      in_text: "actividades",
      in_text_translation: "activities",
      english: "activity",
      spanish: "la actividad",
    },
    {
      in_text: "emociones",
      in_text_translation: "emotions",
      english: "emotion",
      spanish: "la emoción",
    },
    {
      in_text: "danza",
      in_text_translation: "dance",
      english: "dance",
      spanish: "la danza",
    },
    {
      in_text: "teatro",
      in_text_translation: "theater",
      english: "theater",
      spanish: "el teatro",
    },
    {
      in_text: "escultura",
      in_text_translation: "sculpture",
      english: "sculpture",
      spanish: "la escultura",
    },
    {
      in_text: "pintura",
      in_text_translation: "painting",
      english: "painting",
      spanish: "la pintura",
    },
    {
      in_text: "especie",
      in_text_translation: "species",
      english: "species",
      spanish: "la especie",
    },
    {
      in_text: "capaz",
      in_text_translation: "capable",
      english: "capable",
      spanish: "capaz",
    },
    {
      in_text: "extinguirse",
      in_text_translation: "extinguishing",
      english: "extinguish",
      spanish: "extinguirse",
    },
    {
      in_text: "transforma",
      in_text_translation: "transforms us",
      english: "transform",
      spanish: "transformar",
    },
    {
      in_text: "uso",
      in_text_translation: "use",
      english: "use",
      spanish: "usar",
    },
    {
      in_text: "procesador",
      in_text_translation: "processor",
      english: "processor",
      spanish: "el procesador",
    },
    {
      in_text: "científica",
      in_text_translation: "scientific",
      english: "scientific",
      spanish: "científico",
    },
    {
      in_text: "calculadora",
      in_text_translation: "calculator",
      english: "calculator",
      spanish: "la calculadora",
    },
    {
      in_text: "sofisticada",
      in_text_translation: "sophisticated",
      english: "sophisticated",
      spanish: "sofisticado",
    },
    {
      in_text: "finalmente",
      in_text_translation: "finally",
      english: "kill",
      spanish: "matar",
    },
    {
      in_text: "efectividad",
      in_text_translation: "effectively",
      english: "effectively",
      spanish: "la efectividad",
    },
    {
      in_text: "eficiencia",
      in_text_translation: "efficiently",
      english: "efficiently",
      spanish: "la eficiencia",
    },
  ],

  // Challenging words
  challenging_words: [
    {
      in_text: "seres",
      in_text_translation: "beings",
      english: "beings",
      spanish: "seres",
    },
    {
      in_text: "sin",
      in_text_translation: "without",
      english: "sin",
      spanish: "without",
    },
    {
      in_text: "aquello",
      in_text_translation: "that",
      english: "that",
      spanish: "aquello",
    },
    {
      in_text: "aprovechar",
      in_text_translation: "take advantage of",
      english: "take advantage of",
      spanish: "aprovechar",
    },
    {
      in_text: "ni",
      in_text_translation: "even",
      english: "even",
      spanish: "ni",
    },
    {
      in_text: "ilesos",
      in_text_translation: "unharmed",
      english: "unharmed",
      spanish: "ileso",
    },
    {
      in_text: "miles",
      in_text_translation: "thousands",
      english: "thousand",
      spanish: "mil",
    },
    {
      in_text: "listo",
      in_text_translation: "smart",
      english: "smart",
      spanish: "listo",
    },
    {
      in_text: "tonto",
      in_text_translation: "silly",
      english: "silly",
      spanish: "tonto",
    },
    {
      in_text: "sino",
      in_text_translation: "but",
      english: "but",
      spanish: "sino",
    },
    {
      in_text: "final",
      in_text_translation: "at the end",
      english: "at the end",
      spanish: "al final",
    },
    {
      in_text: "resulta",
      in_text_translation: "turns out that",
      english: "turns out that",
      spanish: "resulta que",
    },
    {
      in_text: "matar",
      in_text_translation: "kill",
      english: "kill",
      spanish: "matar",
    },
    {
      in_text: "guerra",
      in_text_translation: "war",
      english: "war",
      spanish: "la guerra",
    },
    {
      in_text: "compartir",
      in_text_translation: "share",
      english: "share",
      spanish: "compartir",
    },
    {
      in_text: "alrededor",
      in_text_translation: "around",
      english: "around",
      spanish: "alrededor",
    },
    {
      in_text: "conjunto",
      in_text_translation: "set",
      english: "set",
      spanish: "el conjunto",
    },
    {
      in_text: "leyes",
      in_text_translation: "laws",
      english: "law",
      spanish: "la ley",
    },
    {
      in_text: "escritura",
      in_text_translation: "writing",
      english: "writing",
      spanish: "la escritura",
    },
    {
      in_text: "gracias",
      in_text_translation: "thanks to",
      english: "thanks to",
      spanish: "gracias a",
    },
    {
      in_text: "pensar",
      in_text_translation: "think",
      english: "think",
      spanish: "pensar",
    },
    {
      in_text: "vinculado",
      in_text_translation: "linked",
      english: "link",
      spanish: "vincular",
    },
    {
      in_text: "acuerdo",
      in_text_translation: "agree on",
      english: "agree ",
      spanish: "estar de acuerdo en",
    },
    {
      in_text: "profunda",
      in_text_translation: "deep",
      english: "deep",
      spanish: "profundo",
    },
    {
      in_text: "gustos",
      in_text_translation: "tastes",
      english: "taste",
      spanish: "el gusto",
    },
    {
      in_text: "entorno",
      in_text_translation: "enviroment",
      english: "enviroment",
      spanish: "el entorno",
    },
    {
      in_text: "diferencia",
      in_text_translation: "unlike",
      english: "unlike",
      spanish: "a diferencia de",
    },
    {
      in_text: "empezar",
      in_text_translation: "start",
      english: "start",
      spanish: "empezar",
    },
    {
      in_text: "desarrolladas",
      in_text_translation: "developed",
      english: "develop",
      spanish: "desarrollar",
    },
    {
      in_text: "tendríamos",
      in_text_translation: "we would have to",
      english: "have",
      spanish: "tener",
    },
    {
      in_text: "videojuego",
      in_text_translation: "video game",
      english: "video game",
      spanish: "videojuego",
    },
    {
      in_text: "lápiz",
      in_text_translation: "pencil",
      english: "pencil",
      spanish: "el lápiz",
    },
    {
      in_text: "entonces",
      in_text_translation: "so",
      english: "so",
      spanish: "entonces",
    },
    {
      in_text: "humilde",
      in_text_translation: "humble",
      english: "humble",
      spanish: "humilde",
    },
    {
      in_text: "olvidar",
      in_text_translation: "forget",
      english: "olvidar",
      spanish: "forget",
    },
    {
      in_text: "llegar",
      in_text_translation: "reach",
      english: "reach",
      spanish: "llegar",
    },
    {
      in_text: "hacer",
      in_text_translation: "make",
      english: "make",
      spanish: "hacer",
    },
    {
      in_text: "grande",
      in_text_translation: "big",
      english: "big",
      spanish: "grande",
    },
    {
      in_text: "cerca",
      in_text_translation: "close",
      english: "close",
      spanish: "cerca",
    },
    {
      in_text: "pequeñas",
      in_text_translation: "small",
      english: "small",
      spanish: "pequeño",
    },
    {
      in_text: "rápido",
      in_text_translation: "fast",
      english: "fast",
      spanish: "rápido",
    },
    {
      in_text: "lejos",
      in_text_translation: "farther",
      english: "farther",
      spanish: "lejos",
    },
    {
      in_text: "desplazarnos",
      in_text_translation: "move",
      english: "move",
      spanish: "desplazarnos",
    },
    {
      in_text: "más",
      in_text_translation: "more",
      english: "more",
      spanish: "más",
    },
    {
      in_text: "ejemplo",
      in_text_translation: "example",
      english: "example",
      spanish: "ejemplo",
    },
    {
      in_text: "permite",
      in_text_translation: "allows us",
      english: "allow",
      spanish: "permitir",
    },
    {
      in_text: "capacidad",
      in_text_translation: "capability",
      english: "capability",
      spanish: "la capacidad",
    },
    {
      in_text: "mejoramiento",
      in_text_translation: "improvment",
      english: "improve",
      spanish: "mejorar",
    },
    {
      in_text: "conocimiento",
      in_text_translation: "knowledge",
      english: "knowledge",
      spanish: "el conocimiento",
    },
    {
      in_text: "antiguo",
      in_text_translation: "old",
      english: "old",
      spanish: "antiguo",
    },
    {
      in_text: "raíces",
      in_text_translation: "roots",
      english: "roots",
      spanish: "la raíz",
    },
    {
      in_text: "muy",
      in_text_translation: "very",
      english: "very",
      spanish: "muy",
    },
    {
      in_text: "escuchemos",
      in_text_translation: "we hear",
      english: "hear",
      spanish: "escuchar",
    },
    {
      in_text: "despoja",
      in_text_translation: "strips us",
      english: "strips us",
      spanish: "despojar",
    },
    {
      in_text: "menos",
      in_text_translation: "less",
      english: "less",
      spanish: "menos",
    },
    {
      in_text: "relacionamos",
      in_text_translation: "associate",
      english: "associate",
      spanish: "relacionar",
    },
    {
      in_text: "cosas",
      in_text_translation: "things",
      english: "things",
      spanish: "la coas",
    },
  ],

  // False Cognates
  false_cognates: [
    {
      in_text: "conservar",
      in_text_translation: "preserve",
      english: "preserve",
      spanish: "conservar",
    },
    {
      in_text: "única",
      in_text_translation: "only",
      english: "only",
      spanish: "único",
    },
    {
      in_text: "finalmente",
      in_text_translation: "ultimately",
      english: "ultimately",
      spanish: "finalmente",
    },
    {
      in_text: "precisión",
      in_text_translation: "accurately",
      english: "accurately",
      spanish: "la precisión",
    },
  ],

  // Subjunctives
  subjunctives: [
    {
      in_text: "estuvieran",
      in_text_translation: "as if they were",
      english: "they were",
      spanish: "ellos estuvieran",
    },
  ],
});
