const Video_Tamaño_Universo = new ActivityContent({
  creator: Creator_Curiosamente,

  title: "¿Qué tan grande es el universo?",

  type: "video",

  url: "https://www.youtube.com/watch?v=Pt2U47Fu8ZA&ab_channel=CuriosaMente",

  youtube_embed_url: "https://www.youtube.com/embed/Pt2U47Fu8ZA",

  text: [
    {
      title: "Introducción",
      paragraphs: [
        "¿De que tamaño es el universo?",
        "Es parte de nuestra naturaleza preguntarnos, ¿que hay más allá?",
        "De bebés, el mundo que conocemos es solo nuestra casa.",
        "Después, conocemos nuestra ciudad, quizás otros países.",
        "Luego sabemos que hay otros planetas y millones de estrellas.",
        "¿Qué tan grande es el universo?",
      ],
    },
    {
      title: "El tamaño del universo",
      paragraphs: [
        "Para los antiguos, el Universo era simplemente la Tierra , que sin medios de transporte como los de ahora, les debía parecer enorme.",
        "La tierra la concebían como rodeada del Sol, la Luna, los planetas, y una esfera negra con perforaciones, las estrellas, que dejaban ver un fuego que estaba oculto.",
        "El primero en tratar de medir el universo fue Arquímedes de Siracusa. El quiso calcular cuantos granos de arena cabían en el cosmos.",
        "Así que primero, tuvo que medir el cosmos. Usó el modelo de Aristarco, con el Sol al centro.",
        "Arquímedes se seguia imaginando que la orilla del universo, era una esfera con las estrellas fijas, por que no tenia instrumentos para detectar que se mueven a diferentes velocidades.",
        "Así que usando ángulos y cálculos matemáticos, llego a la conclusión de que el universo debia medir unos 100 billones de estadios. O sea, unos 19 billones de kilómetros o, como dicen los cientificos 2 años luz.",
      ],
    },
    {
      title: "¿Qué sabemos ahora?",
      paragraphs: [
        "En la actualidad sabemos que la estrella más cercana al Sol, Próxima centauri está muuucho más lejos 4,2 años luz, y de ahi para arriba.",
        "Para hacernos una idea del tamaño del universo. Empecemos por algo familiar, la Tierra, su diámetro es de unos 12 mil kilómetros. La Tierra forma parte del sistema solar que mide 4,500 millones de kilometros.",
        "El sistema solar forma parte de la galaxia que llamamos Vía Láctea que es 10 mil veces mayor, 500 billones de kilómetros en su parte mas larga. Unos cincuenta años luz.",
      ],
    },
    {
      title: "Otras galaxias",
      paragraphs: [
        "Hasta 1920 , los astronomos pensaban que todas las estrellas del universo estaban contenidas aqui. Pero resulta que se encontraron otras galaxias.",
        "En los años 90' el telescopio Hubble encontrándose en un pedacito del cielo que parecía vació pudo fotografiar esta imagen. Cada manchita brillante es una galaxia, con sus propias estrellas y planetas.",
      ],
    },
    {
      title: "La vía láctea",
      paragraphs: [
        "Nuestra Vía Láctea forma parte de una familia llamada el Grupo Local, que tiene unas 50 galaxias. Su diámetro es de… agárrate… 10 millones de años luz.",
        "¿Ya te mareaste? Aún no terminamos.",
        "El grupo local a su vez forma parte del Super Cúmulo de Virgo, de 200 millones de años luz, que a su vez forma parte del Complejo de Supercúmulos Piscis-Cetus, de mil millones de años luz.",
        "El universo visible tiene un límite: como la luz tarda en llegar hasta nosotros, sólo podemos ver objetos cuya luz haya viajado una distancia equivalente a la edad del universo de 13 mil millones de años.",
        "Como estos objetos también se alejan, los cálculos dicen que el universo visible tiene un diámetro de 93 mil millones de años luz. Un dato curioso.",
      ],
    },
    {
      title: "¿Qué hay más allá?",
      paragraphs: [
        "Si lo más grande que conocemos es el universo visible y lo más pequeño es la distancia de Plank (una medida mucho más pequeña que un átomo e incluso más pequeña que una partícula subatómica). ¿Qué estaría justo en medio?",
        "La respuesta sería: un protozoario.",
        "¿Y más allá del universo observable? ¿Cuánto medirá el Universo en su totalidad?",
        "Quién sabe.",
        "El universo bien podría ser infinito.",
        "Los problemas que tenemos en nuestra casa de repente no parecen tan grandes ¿Verdad?",
        "¡Curiosamente!",
      ],
    },
  ],

  // Cognates
  cognates: [
    {
      in_text: "telescopio",
      in_text_translation: "telescope",
      english: "telescope",
      spanish: "el telescopio",
    },
    {
      in_text: "telescopio",
      in_text_translation: "telescope",
      english: "telescope",
      spanish: "el telescopio",
    },
    {
      in_text: "galaxia",
      in_text_translation: "galaxies",
      english: "galaxy",
      spanish: "la galaxia",
    },
    {
      in_text: "astrónomos",
      in_text_translation: "astronomers",
      english: "astronomer",
      spanish: "el astrónomo",
    },
    {
      in_text: "familiar",
      in_text_translation: "familiar",
      english: "familiar",
      spanish: "familiar",
    },
    {
      in_text: "universo",
      in_text_translation: "universe",
      english: "universe",
      spanish: "el universo",
    },
    {
      in_text: "naturaleza",
      in_text_translation: "nature",
      english: "nature",
      spanish: "la naturaleza",
    },
    {
      in_text: "bebés",
      in_text_translation: "babies",
      english: "baby",
      spanish: "el bebé",
    },
    {
      in_text: "planetas",
      in_text_translation: "planets",
      english: "planet",
      spanish: "el planeta",
    },
    {
      in_text: "transporte",
      in_text_translation: "transportation",
      english: "transport",
      spanish: "el transporte",
    },
    {
      in_text: "esfera",
      in_text_translation: "sphere",
      english: "sphere",
      spanish: "la esfera",
    },
    {
      in_text: "perforaciones",
      in_text_translation: "perforations",
      english: "perforations",
      spanish: "perforaciones",
    },
    {
      in_text: "calcular",
      in_text_translation: "calculate",
      english: "calculate",
      spanish: "calcular",
    },
    {
      in_text: "cosmos",
      in_text_translation: "cosmos",
      english: "cosmos",
      spanish: "cosmos",
    },
    {
      in_text: "instrumentos",
      in_text_translation: "instruments",
      english: "instrument",
      spanish: "el instrumento",
    },
    {
      in_text: "detectar",
      in_text_translation: "detect",
      english: "detect",
      spanish: "detectar",
    },
    {
      in_text: "ángulos",
      in_text_translation: "angles",
      english: "angle",
      spanish: "el ángulo",
    },
    {
      in_text: "conclusión",
      in_text_translation: "conclusion",
      english: "conclusion",
      spanish: "conclusión",
    },
    {
      in_text: "kilómetros",
      in_text_translation: "kilometers",
      english: "kilometer",
      spanish: "el kilómetro",
    },
    {
      in_text: "diámetro",
      in_text_translation: "diameter",
      english: "diameter",
      spanish: "diámetro",
    },
    {
      in_text: "visible",
      in_text_translation: "visible",
      english: "visible",
      spanish: "visible",
    },
    {
      in_text: "límite",
      in_text_translation: "limit",
      english: "limit",
      spanish: "el límite",
    },
    {
      in_text: "objetos",
      in_text_translation: "objects",
      english: "objects",
      spanish: "el objeto",
    },
    {
      in_text: "diámetro",
      in_text_translation: "diameter",
      english: "diameter",
      spanish: "el diámetro",
    },
    {
      in_text: "distancia",
      in_text_translation: "distance",
      english: "distance",
      spanish: "la distancia",
    },
    {
      in_text: "partícula",
      in_text_translation: "particle",
      english: "particle",
      spanish: "la partícula",
    },
    {
      in_text: "observable",
      in_text_translation: "observable",
      english: "observable",
      spanish: "el observable",
    },
    {
      in_text: "totalidad",
      in_text_translation: "totality",
      english: "totality",
      spanish: "la totalidad",
    },
    {
      in_text: "infinito",
      in_text_translation: "infinite",
      english: "infinite",
      spanish: "el infinito",
    },
    {
      in_text: "problemas",
      in_text_translation: "problems",
      english: "problem",
      spanish: "el problema",
    },
    {
      in_text: "concebían",
      in_text_translation: "conceived",
      english: "conceive",
      spanish: "concebir",
    },
    {
      in_text: "granos",
      in_text_translation: "grains",
      english: "grain",
      spanish: "el grano",
    },
    {
      in_text: "sistema",
      in_text_translation: "system",
      english: "system",
      spanish: "el system",
    },
    {
      in_text: "solar",
      in_text_translation: "solar",
      english: "solar",
      spanish: "solar",
    },
    {
      in_text: "equivalente",
      in_text_translation: "equivalent",
      english: "equivalent",
      spanish: "equivalente",
    },
    {
      in_text: "forma",
      in_text_translation: "forms",
      english: "form",
      spanish: "formar",
    },
    {
      in_text: "mucho",
      in_text_translation: "much",
      english: "much",
      spanish: "mucho",
    },
  ],

  // Challenging words
  challenging_words: [
    {
      in_text: "más",
      in_text_translation: "more",
      english: "more",
      spanish: "más",
    },
    {
      in_text: "mayor",
      in_text_translation: "greater",
      english: "greater",
      spanish: "mayor",
    },
    {
      in_text: "larga",
      in_text_translation: "long",
      english: "long",
      spanish: "largo",
    },
    {
      in_text: "encontraron",
      in_text_translation: "found",
      english: "find",
      spanish: "encontrar",
    },
    {
      in_text: "aquí",
      in_text_translation: "here",
      english: "here",
      spanish: "aquí",
    },
    {
      in_text: "pensaban",
      in_text_translation: "used to think",
      english: "think",
      spanish: "pensar",
    },
    {
      in_text: "parte",
      in_text_translation: "part",
      english: "part",
      spanish: "la parte",
    },
    {
      in_text: "también",
      in_text_translation: "also",
      english: "also",
      spanish: "también",
    },
    {
      in_text: "cuya",
      in_text_translation: "whose",
      english: "whose",
      spanish: "cuyo",
    },
    {
      in_text: "medio",
      in_text_translation: "middle",
      english: "middle",
      spanish: "el medio",
    },
    {
      in_text: "justo",
      in_text_translation: "right",
      english: "right",
      spanish: "justo",
    },
    {
      in_text: "incluso",
      in_text_translation: "even",
      english: "even",
      spanish: "incluso",
    },
    {
      in_text: "respuesta",
      in_text_translation: "answer",
      english: "answer",
      spanish: "la respuesta",
    },
    {
      in_text: "veces",
      in_text_translation: "times",
      english: "times",
      spanish: "la vez",
    },
    {
      in_text: "Empecemos",
      in_text_translation: "let's start",
      english: "start",
      spanish: "empezar",
    },
    {
      in_text: "científicos",
      in_text_translation: "scientists",
      english: "scientific",
      spanish: "el científico",
    },
    {
      in_text: "cabían",
      in_text_translation: "fit",
      english: "fit",
      spanish: "caber",
    },
    {
      in_text: "arena",
      in_text_translation: "sand",
      english: "sand",
      spanish: "la arena",
    },
    {
      in_text: "oculto",
      in_text_translation: "hidden",
      english: "hidden",
      spanish: "oculto",
    },
    {
      in_text: "rodeada",
      in_text_translation: "surrounded",
      english: "surrounded",
      spanish: "rodeada",
    },
    {
      in_text: "parecer",
      in_text_translation: "seem",
      english: "seem",
      spanish: "parecer",
    },
    {
      in_text: "quizás",
      in_text_translation: "maybe",
      english: "maybe",
      spanish: "quizás",
    },
    {
      in_text: "solo",
      in_text_translation: "only",
      english: "only",
      spanish: "solo",
    },
    {
      in_text: "conocemos",
      in_text_translation: "know",
      english: "know",
      spanish: "conocer",
    },
    {
      in_text: "alejar",
      in_text_translation: "move away",
      english: "move away",
      spanish: "alejar",
    },
    {
      in_text: "llegar",
      in_text_translation: "arrive",
      english: "arrive",
      spanish: "llegar",
    },
    {
      in_text: "terminamos",
      in_text_translation: "finish",
      english: "finish",
      spanish: "terminar",
    },
    {
      in_text: "mareaste",
      in_text_translation: "got dizzy",
      english: "get dizzy",
      spanish: "mearear",
    },
    {
      in_text: "agárrate",
      in_text_translation: "hold on",
      english: "hold on",
      spanish: "agarrar",
    },
    {
      in_text: "Láctea",
      in_text_translation: "milky",
      english: "milky",
      spanish: "láctea",
    },
    {
      in_text: "Vía",
      in_text_translation: "way",
      english: "way",
      spanish: "la vía",
    },
    {
      in_text: "brillante",
      in_text_translation: "bright",
      english: "bright",
      spanish: "brillante",
    },
    {
      in_text: "vacío",
      in_text_translation: "empty",
      english: "empty",
      spanish: "vacío",
    },
    {
      in_text: "manchita",
      in_text_translation: "little speck",
      english: "little speck",
      spanish: "el cielo",
    },
    {
      in_text: "cielo",
      in_text_translation: "sky",
      english: "sky",
      spanish: "el cielo",
    },
    {
      in_text: "pedacito",
      in_text_translation: "little piece",
      english: "little piece",
      spanish: "el pedacito",
    },
    {
      in_text: "años",
      in_text_translation: "years",
      english: "year",
      spanish: "el año",
    },
    {
      in_text: "luz",
      in_text_translation: "ligh",
      english: "light",
      spanish: "la luz",
    },
    {
      in_text: "medir",
      in_text_translation: "measure",
      english: "measure",
      spanish: "medir",
    },
    {
      in_text: "velocidades",
      in_text_translation: "speeds",
      english: "speed",
      spanish: "la velocidad",
    },
    {
      in_text: "mueven",
      in_text_translation: "move",
      english: "move",
      spanish: "mover",
    },
    {
      in_text: "orilla",
      in_text_translation: "shore",
      english: "shore",
      spanish: "la orilla",
    },
    {
      in_text: "fijas",
      in_text_translation: "fixed",
      english: "fixed",
      spanish: "fijas",
    },
    {
      in_text: "fuego",
      in_text_translation: "fire",
      english: "fire",
      spanish: "fuego",
    },
    {
      in_text: "Sol",
      in_text_translation: "Sun",
      english: "Sun",
      spanish: "el Sol",
    },
    {
      in_text: "Luna",
      in_text_translation: "Moon",
      english: "Moon",
      spanish: "la Luna",
    },
    {
      in_text: "tamaño",
      in_text_translation: "size",
      english: "size",
      spanish: "el tamaño",
    },
    {
      in_text: "mundo",
      in_text_translation: "world",
      english: "world",
      spanish: "el mundo",
    },
    {
      in_text: "casa",
      in_text_translation: "house",
      english: "house",
      spanish: "la casa",
    },
    {
      in_text: "ciudad",
      in_text_translation: "city",
      english: "city",
      spanish: "la ciudad",
    },
    {
      in_text: "países",
      in_text_translation: "countries",
      english: "country",
      spanish: "el país",
    },
    {
      in_text: "estrella",
      in_text_translation: "stars",
      english: "stars",
      spanish: "la estrella",
    },
    {
      in_text: "grande",
      in_text_translation: "big",
      english: "big",
      spanish: "grande",
    },
    {
      in_text: "Tierra",
      in_text_translation: "Earth",
      english: "Earth",
      spanish: "La Tierra",
    },
    {
      in_text: "medios",
      in_text_translation: "means",
      english: "mean",
      spanish: "el medio",
    },
    {
      in_text: "cercana",
      in_text_translation: "nearby",
      english: "nearby",
      spanish: "cercana",
    },
    {
      in_text: "tamaño",
      in_text_translation: "size",
      english: "size",
      spanish: "tamaño",
    },
  ],

  // False Cognates
  false_cognates: [
    {
      in_text: "billones",
      in_text_translation: "trillion",
      english: "trillion",
      spanish: "el billón",
    },
    {
      in_text: "actualidad",
      in_text_translation: "present",
      english: "present",
      spanish: "la actualidad",
    },
    {
      in_text: "dato",
      in_text_translation: "fact",
      english: "fact",
      spanish: "el dato",
    },
  ],

  // Subjunctives
  subjunctives: [
    {
      in_text: "haya",
      in_text_translation: "had traveled",
      english: "had traveled",
      spanish: "haber viajado",
    },
  ],
});
